### ISSUE TITLE
mail.send v3 APi documentation doesn't mention X-Message-ID

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#2797]
The documentation at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html doesn't mention the `X-Message-ID` that's passed back in the returned headers at all. However, SendGrid recommends that users store this data to correlate to their Event Webhook data, and this data is very useful for Support troubleshooting.

**Comment by Logan1x** [comment]
I would like to work on this issue @jacobmovingfwd . How can i help?

**Comment by Logan1x** [comment]
@jacobmovingfwd  you can assign me this issue 😊

**Comment by Logan1x** [comment]
CC : @ksigler7

**Comment by jacobmovingfwd** [comment]
@Logan1x it's not assigned to me, and I don't think I have permissions for that (at least I have no idea how)

**Comment by ksigler7** [comment]
@Logan1x sure, go for it!

**Comment by Logan1x** [comment]
@ksigler7  can you tell me where to find `X-Message-ID` ?

**Comment by kylearoberts** [comment]
@Logan1x 

Sorry for the delay in getting back to you. The X-Message-ID is a header in the response to a mail send request. Please let us know if you need further details.

**Comment by ansh-ptel** [comment]
@Logan1x Are you still working on this or not?if not then can I work on this?

**Comment by Logan1x** [comment]
@ansh-ptel As of now i am not working on this.so if you want to work on this then go ahead 😊👍

**Comment by ansh-ptel** [comment]
@kylearoberts I need to know where to put x-message id in the docs and what's the value of X-message it?

**Comment by ansh-ptel** [comment]
@kylearoberts is [this](https://sendgrid.com/docs/Glossary/message_id.html)
 the x-message-id?

**Comment by Logan1x** [comment]
@ksigler7 @jacobmovingfwd please help him.

**Comment by ksigler7** [comment]
@Logan1x thanks so much for the call out!

I think the todo here is to add in an example response at the bottom of this page that includes the `X-Message-ID` with a note after that says something like this - 
{% info %}
If you are using the [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html), it's best practice to store your `X-Message-ID` data help with deduplications in your webhook data.
{% endinfo %}

You can get an example response by making an API call to the V3 mail send. @kylearoberts is going to help out with that part.

**Comment by kylearoberts** [comment]
@ansh-ptel Sorry for the delay. The X-Message-ID is a header returned when making a mail send. Here is a v3 mail send [response example](https://www.screencast.com/t/PKiJiBmG).

As for the Message-ID information you linked to you can actually find the X-Message-ID in the [Message ID](https://www.screencast.com/t/hl7wJBd5V76J) of events like delivered events that our Event Webhook posts.

So the X-Message-ID can be used to track events that the Event Webhook posts. The X-Message-ID can be used to find all corresponding Message-IDs. Looking at the doc you pointed out [here](https://sendgrid.com/docs/Glossary/message_id.html), I can see it needs a little updating which I will do. Activity Feed labels Message-ID as "msgid" and Event Webhook labels it as "sg_message_id" in the posts it makes.

**Comment by jacobmovingfwd** [comment]
It's also returned in SMTPAPI calls, in the response body. I believe it's returned in the v3 APi call as well? In SMTP & v2, it's not called `X-Message-ID`, but the ID itself is passed.

**Comment by ansh-ptel** [comment]
@ksigler7 @kylearoberts @jacobmovingfwd thanks for your responses. and i will complete this thing as soon as possible.

**Comment by ansh-ptel** [comment]
@jacobmovingfwd @kylearoberts @ksigler7 I found the x-message id. 

- X-Message-Id : XBg2anf2TqCy6WXKQFhieQ

**Comment by ansh-ptel** [comment]
where I have to include this X-message-id in Documentation?
@jacobmovingfwd @ksigler7 @kylearoberts

**Comment by jacobmovingfwd** [comment]
I would include it first & foremost in the Glossary, then link to it in:
mail.send v3, SMTP send, and Event Webhook.

**Comment by ksigler7** [comment]
I think the todo here is to add in an example response at the bottom of [this page](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) that includes the `X-Message-ID` with a note after that says something like this -
{% info %}
If you are using the Event Webhook, it's best practice to store your X-Message-ID data help with deduplications in your webhook data.
{% endinfo %}

**Comment by ksigler7** [comment]
@jacobmovingfwd - let's not do a glossary entry for this one, for clarities sake, let's just create a new issue for an X-Message-ID glossary entry

**Comment by ksigler7** [comment]
added a new issue for the glossary entry here: https://github.com/sendgrid/docs/issues/3103

**Comment by ansh-ptel** [comment]
`{% info %}
If you are using the Event Webhook, it's best practice to store your X-Message-ID data help with deduplications in your webhook data.
{% endinfo %}` 

@ksigler7  it is already present there and there is also another x-message-id ` X-Message-Id →kA5kcHA8SVGtVh5S9rAUew`

x-message-id and this info is already present on that page.so what is the task?

**Comment by idontusenumbers** [comment]
I just spent way more time researching x-message-id than I care to admit. How is this issue closed? MessageID seems like a fundamental aspect of sending email using sendgrid. Stashing it in the header and then not showing the response header information in the API docs is really frustrating.

The webhook docs don't mention it:
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html

I couldn't find an official javadoc for the java library, but this one doesn't mention it:
http://javadox.com/com.sendgrid/sendgrid-java/2.2.2/com/sendgrid/SendGrid.Response.html

The v3 API doesn't mention it:
https://sendgrid.com/docs/API_Reference/api_v3.html

I'm not sure how it's different but this v3 DOES reference it (which begs the question what's going on with the two sets of docs):
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

It would be really helpful to have interlinking between all the documentation or at least references inline indicating there these values come from or go to.

**Comment by ksigler7** [comment]
This issue was closed because it was a specific issue about clarifying x-message-id in the event webhook documentation that was solved. Please feel free to file a new issue.

**Comment by idontusenumbers** [comment]
@jacobmovingfwd 
Without the ID, sendgrid is a blackbox you just dump email into and hope for the best. Hard bounce handling is essential for many business needs and avoiding honeypot spam boxes. Sure it's not absolutely required, but theres really one thing sendgrid does, and that's send email, and the email it sends is identified by one thing, the id.

@ksigler7
But it's not solved:
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html

Do I really need to make 3 new tickets, one for each page? Can someone at sendgrid make those tickets?

**Comment by ksigler7** [comment]
@idontusenumbers - yes, normally it's considered best practice in the open source community to file a new issue if you have an issue, honestly because it usually gets handled much faster, but don't worry, someone at SendGrid will handle it. Just FYI, we're in a repo freeze right now, and this isn't an emergency, so it's not going to get addressed until after our freeze. For more info, [check out this issue](https://github.com/sendgrid/docs/issues/3728).

Also, next time you find yourself spending a ton of time stuck on something, you should reach out to our awesome support team. You can access support contact options by logging into https://support.sendgrid.com.

**Comment by idontusenumbers** [comment]
We're exploring if sendgrid meets are technical requirements; being able to know which specific emails bounced was one of them.

**Comment by alionas3** [comment]
Hello,
 is there a way to map X-MESSAGE-ID from POST mail/send with GET /messages query=msg_id="MESSAGE ID FROM X-MESSAGE-ID" ? why this does not work?

**Comment by kylearoberts** [comment]
@alionas3 

I think what you are looking for is this:

```
curl -X GET \
  'https://api.sendgrid.com/v3/messages?limit=1000&query=msg_id+LIKE+%223CictmYXRcyZrrpy6Scw0w%25%22' \
  -H 'Authorization: Bearer <API KEY>'
```

So in this case you would be using:

`msg_id LIKE "3CictmYXRcyZrrpy6Scw0w%"`

Which using your description from above should be:

`query=msg_id LIKE "MESSAGE ID FROM X-MESSAGE-ID%"`

The main things here are using the LIKE parameter instead of = and adding a % on the end as a wild card. The reason for the wild card is that the ID of a message has some data added onto it as it gets processed.

Example:

`X-MESSAGE-ID: 3CictmYXRcyZrrpy6Scw0w`

`msgid: 3CictmYXRcyZrrpy6Scw0w.filter0454p1iad2-22931-5D51CA44-3.0`

You can see the ID you get when you first send the message to SendGrid is the same, but after that there is some other data added onto it.

I hope this helps. Please let us know if you have further questions.

**Comment by andreconghau** [comment]
@kylearoberts 
It works fine.
thank you so much!

**Comment by chapacua** [comment]
@kylearoberts It's works like as charm.

**Comment by muke1908** [comment]
In doc it's written that `X-MESSAGE-ID` is to correlate with the webhook data. However, we don't get `X-MESSAGE-ID` back in webhook response. Is it expected that we have to do partial match with `sg_message_id` from webhook response?

**Comment by PalTamasWBA** [comment]
@muke1908 Think pretty much that or custom args.
Matching the X-MESSAGE-ID to sg_message_id seems like a hack to me. Remove everything after the dot character then use the remaining string to search and match? What if the format changes? ¯\_(ツ)_/¯
